const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    APP_CHANGE_LANGUAGE: 'APP_CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',

    FETCH_GENDER_START : 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_START : 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_START : 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    FETCH_PRICE_SUCCESS: 'FETCH_PRICE_SUCCESS',
    FETCH_PRICE_FAIL: 'FETCH_PRICE_FAIL',

    FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
    FETCH_PROVINCE_FAIL: 'FETCH_PROVINCE_FAIL',

    FETCH_PAYMENT_SUCCESS: 'FETCH_PAYMENT_SUCCESS',
    FETCH_PAYMENT_FAIL: 'FETCH_PAYMENT_FAIL',

    // FETCH_TIME_START : 'FETCH_TIME_START',
    // FETCH_TIME_SUCCESS: 'FETCH_TIME_SUCCESS',
    // FETCH_TIME_FAIL: 'FETCH_TIME_FAIL',

    ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
    ADD_NEW_USER_FAIL: 'ADD_NEW_USER_FAIL',

    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAIL: 'GET_ALL_USERS_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    GET_TOP_DOCTOR_HOME_SUCCESS: 'GET_TOP_DOCTOR_HOME_SUCCESS',
    GET_TOP_DOCTOR_HOME_FAIL: 'GET_TOP_DOCTOR_HOME_FAIL',

    GET_ALL_DOCTORS_SUCCESS: 'GET_ALL_DOCTORS_SUCCESS',
    GET_ALL_DOCTORS_FAIL: 'GET_ALL_DOCTORS_FAIL',

    SAVE_INFOR_DOCTOR_SUCCESS: 'SAVE_INFOR_DOCTOR_SUCCESS',
    SAVE_INFOR_DOCTOR_FAIL: 'SAVE_INFOR_DOCTOR_FAIL',

    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAIL: 'GET_DETAIL_DOCTOR_FAIL',

    GET_SCHEDULE_TIME_SUCCESS: 'GET_SCHEDULE_TIME_SUCCESS',
    GET_SCHEDULE_TIME_FAIL: 'GET_SCHEDULE_TIME_FAIL',

    GET_GENERAL_CLINIC_SUCCESS: 'GET_GENERAL_CLINIC_SUCCESS',
    GET_GENERAL_CLINIC_FAIL: 'GET_GENERAL_CLINIC_FAIL',

    GET_INTRO_DOCTOR_SUCCESS: 'GET_INTRO_DOCTOR_SUCCESS',
    GET_INTRO_DOCTOR_FAIL: 'GET_INTRO_DOCTOR_FAIL',

    GET_DOCTOR_FOR_BOOKING_SUCCESS: 'GET_DOCTOR_FOR_BOOKING_SUCCESS',
    GET_DOCTOR_FOR_BOOKING_FAIL: 'GET_DOCTOR_FOR_BOOKING_FAIL',

    POST_PATIENT_BOOKING_SUCCESS: 'POST_PATIENT_BOOKING_SUCCESS',
    POST_PATIENT_BOOKING_FAIL: 'POST_PATIENT_BOOKING_FAIL',

    CREATE_INFOR_SPECIALTY_SUCCESS: 'CREATE_INFOR_SPECIALTY_SUCCESS',
    CREATE_INFOR_SPECIALTY_FAIL: 'CREATE_INFOR_SPECIALTY_FAIL',

    GET_ALL_SPECIALTY_SUCCESS: 'GET_ALL_SPECIALTY_SUCCESS',
    GET_ALL_SPECIALTY_FAIL: 'GET_ALL_SPECIALTY_FAIL',

    GET_GENERAL_SPECIALTY_SUCCESS: 'GET_GENERAL_SPECIALTY_SUCCESS',
    GET_GENERAL_SPECIALTY_FAIL: 'GET_GENERAL_SPECIALTY_FAIL',

    DELETE_SPECIALTY_SUCCESS: 'DELETE_SPECIALTY_SUCCESS',
    DELETE_SPECIALTY_FAIL: 'DELETE_SPECIALTY_FAIL',

    UPDATE_SPECIALTY_SUCCESS: 'UPDATE_SPECIALTY_SUCCESS',
    UPDATE_SPECIALTY_FAIL: 'UPDATE_SPECIALTY_FAIL',

    GET_PATIENTS_SUCCESS: 'GET_PATIENTS_SUCCESS',
    GET_PATIENTS_FAIL: 'GET_PATIENTS_FAIL',

    CREATE_INFOR_CLINIC_SUCCESS: 'CREATE_INFOR_CLINIC_SUCCESS',
    CREATE_INFOR_CLINIC_FAIL: 'CREATE_INFOR_CLINIC_FAIL',

    GET_ALL_CLINIC_SUCCESS: 'GET_ALL_CLINIC_SUCCESS',
    GET_ALL_CLINIC_FAIL: 'GET_ALL_CLINIC_FAIL',

    GET_HOME_CLINIC_SUCCESS: 'GET_HOME_CLINIC_SUCCESS',
    GET_HOME_CLINIC_FAIL: 'GET_HOME_CLINIC_FAIL',

    DELETE_CLINIC_SUCCESS: 'DELETE_CLINIC_SUCCESS',
    DELETE_CLINIC_FAIL: 'DELETE_CLINIC_FAIL',

    UPDATE_CLINIC_SUCCESS: 'UPDATE_CLINIC_SUCCESS',
    UPDATE_CLINIC_FAIL: 'UPDATE_CLINIC_FAIL',

    GET_HOME_HANDBOOKS_SUCCESS: 'GET_HOME_HANDBOOKS_SUCCESS',
    GET_HOME_HANDBOOKS_FAIL: 'GET_HOME_HANDBOOKS_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'ADMIN_REGISTER_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    DELETE_USER: 'DELETE_USER'
})

export default actionTypes;